// AUTO-GENERATED by playground/build.ts from showcase/scenes.ts — do not edit.
// One source of truth: the gallery deep-links and the playground examples share these.
import type { Scene } from "../../src/types.js"

export const STARTER = "{\n  \"meta\": {\n    \"aspect\": \"square\",\n    \"theme\": {\n      \"preset\": \"claude\"\n    },\n    \"window\": {\n      \"chrome\": \"mac\",\n      \"title\": \"demo\"\n    },\n    \"align\": \"top\"\n  },\n  \"steps\": [\n    {\n      \"cmd\": \"npm install termscene\"\n    },\n    {\n      \"out\": \"added 1 package in 1.2s\",\n      \"style\": \"dim\"\n    },\n    {\n      \"cmd\": \"termscene render demo.scene.json --out demo.gif\"\n    },\n    {\n      \"out\": \"wrote demo.gif\",\n      \"style\": \"ok\"\n    }\n  ]\n}"

export interface ShowcaseIndexEntry {
  id: string
  name: string
  blurb: string
  sw: string
  scene: Scene
}

// Terminal-LOOK examples — the secondary "style" axis (claude/gemini/warp/…).
export const SHOWCASE_INDEX: ShowcaseIndexEntry[] = [
  {
    "id": "claude-code",
    "name": "Claude Code",
    "blurb": "warm dark · terracotta ❯ · ✻ thinking · ● tool calls",
    "sw": "#d97757",
    "scene": {
      "meta": {
        "aspect": "wide",
        "theme": {
          "preset": "claude"
        },
        "window": {
          "chrome": "mac",
          "title": "claude code"
        },
        "prompt": "❯",
        "fontSize": 24,
        "align": "top",
        "loopOffset": "80%"
      },
      "steps": [
        {
          "cmd": "add a Retry-After header to the 429 responses in the rate limiter",
          "prompt": "❯",
          "typeSpeed": 42
        },
        {
          "out": "✻ Thinking… locating the rate-limit middleware, then setting the header on the 429 branch.",
          "style": "dim"
        },
        {
          "out": [
            "● Grep(pattern: \"429\", glob: \"src/**/*.ts\")",
            "  └─ 3 matches in src/middleware/rateLimit.ts"
          ],
          "style": "accent"
        },
        {
          "out": [
            "● Read(src/middleware/rateLimit.ts)",
            "  └─ Read 84 lines"
          ],
          "style": "accent"
        },
        {
          "wait": 1
        },
        {
          "out": [
            "● Edit(src/middleware/rateLimit.ts +4 -1)",
            "  └─ Set Retry-After from limiter.msBeforeNext on the 429 branch"
          ],
          "style": "accent"
        },
        {
          "out": "● Bash(npm test -- rateLimit)",
          "style": "accent"
        },
        {
          "progress": "jest src/middleware/rateLimit.test.ts",
          "duration": 2.4
        },
        {
          "out": [
            "  PASS  src/middleware/rateLimit.test.ts",
            "  Tests: 9 passed, 9 total"
          ],
          "style": "ok"
        },
        {
          "div": true
        },
        {
          "out": [
            "● Done. 429 responses now send Retry-After in seconds, computed from the",
            "  limiter's reset window, with a test asserting the header value."
          ],
          "style": "ok",
          "stream": 1.6
        }
      ]
    }
  },
  {
    "id": "gemini-cli",
    "name": "Gemini CLI",
    "blurb": "dark slate · blue→violet · ✦ sparkle accents",
    "sw": "#a78bfa",
    "scene": {
      "meta": {
        "aspect": "wide",
        "theme": {
          "preset": "gemini"
        },
        "window": {
          "chrome": "mac",
          "title": "gemini"
        },
        "prompt": ">",
        "fontSize": 24
      },
      "steps": [
        {
          "out": [
            "",
            "  ✦  G E M I N I",
            "  ─────────────",
            "  gemini-2.5-pro  ·  ~/projects/api  ·  ctrl+c to quit",
            ""
          ],
          "style": "accent"
        },
        {
          "cmd": "explain why my rate limiter lets bursts through, then fix it",
          "prompt": "> "
        },
        {
          "progress": "Reading middleware/ratelimit.go",
          "duration": 1.6
        },
        {
          "out": [
            "✦ The bug is a classic fixed-window reset. You count requests per",
            "  calendar minute, so a client can fire N requests at 0:59 and another",
            "  N at 1:00 — 2N within two seconds, all \"within limits.\"",
            "",
            "  A token-bucket fixes this: refill at a steady rate, cap the burst."
          ],
          "stream": 1.6
        },
        {
          "out": [
            "  ┌─ middleware/ratelimit.go",
            "  │  - if reqs[ip].minute != now.Minute() { reqs[ip].n = 0 }",
            "  │  - reqs[ip].n++; if reqs[ip].n > limit { return Deny }",
            "  │  + b := buckets[ip]; b.refill(now, rate, burst)",
            "  │  + if !b.take(1) { return Deny }",
            "  └─"
          ],
          "style": "ok"
        },
        {
          "cmd": "apply it and add a table test",
          "prompt": "> "
        },
        {
          "progress": "Writing ratelimit.go, ratelimit_test.go",
          "duration": 2
        },
        {
          "out": [
            "  ✓ ratelimit.go      (+22 -6)",
            "  ✓ ratelimit_test.go (+41 new)"
          ],
          "style": "ok"
        },
        {
          "cmd": "!go test ./middleware/ -run RateLimit",
          "prompt": "> "
        },
        {
          "out": "ok  \tapi/middleware\t0.118s",
          "style": "ok"
        },
        {
          "out": [
            "✦ Tip: the burst is now configurable via RATELIMIT_BURST.",
            "  Set it to 1 for strict per-request pacing."
          ],
          "style": "accent",
          "stream": 1.4
        }
      ]
    }
  },
  {
    "id": "codex-cli",
    "name": "Codex CLI",
    "blurb": "near-black · sparse green/white · minimal chrome",
    "sw": "#10a37f",
    "scene": {
      "meta": {
        "aspect": "wide",
        "theme": {
          "preset": "codex"
        },
        "window": {
          "chrome": "mac",
          "title": "codex"
        },
        "prompt": "›",
        "fontSize": 24
      },
      "steps": [
        {
          "cmd": "fix the retry backoff in fetcher.py — it caps too early, should be exponential up to 30s"
        },
        {
          "out": "reading fetcher.py, found the backoff loop",
          "style": "dim"
        },
        {
          "out": "● apply patch  src/fetcher.py  +6 -3",
          "style": "accent"
        },
        {
          "out": [
            "    delay = min(base * 2 ** attempt, 30.0)",
            "    delay += random.uniform(0, delay * 0.1)"
          ],
          "style": "dim"
        },
        {
          "div": true
        },
        {
          "cmd": "pytest tests/test_fetcher.py -q"
        },
        {
          "progress": "running 14 tests",
          "duration": 2.2
        },
        {
          "out": [
            "..............",
            "14 passed in 0.91s"
          ],
          "style": "ok"
        },
        {
          "wait": 0.6
        },
        {
          "out": "Backoff now doubles per attempt, caps at 30s, and adds 10% jitter. Tests green.",
          "stream": 1.6
        }
      ]
    }
  },
  {
    "id": "warp",
    "name": "Warp",
    "blurb": "dark · rounded block output · modern GUI terminal",
    "sw": "#4c8dff",
    "scene": {
      "meta": {
        "aspect": "wide",
        "theme": {
          "preset": "warp"
        },
        "window": {
          "chrome": "mac",
          "title": "warp — ~/app"
        },
        "prompt": "❯",
        "fontSize": 24
      },
      "steps": [
        {
          "cmd": "pnpm install"
        },
        {
          "out": [
            "Lockfile is up to date, resolution step is skipped",
            "Packages: +312",
            "Progress: resolved 312, reused 312, downloaded 0, added 312, done"
          ],
          "style": "dim"
        },
        {
          "progress": "installing dependencies",
          "duration": 2.2
        },
        {
          "out": "Done in 1.9s",
          "style": "ok"
        },
        {
          "div": true
        },
        {
          "cmd": "pnpm build"
        },
        {
          "out": [
            "▸ tsc --build            done in 1.4s",
            "▸ vite bundle client     done in 2.1s",
            "▸ vite bundle server     done in 0.9s",
            "✓ build complete → dist/  (482 kB · gzip 138 kB)"
          ],
          "style": "accent"
        },
        {
          "cmd": "pnpm test"
        },
        {
          "out": [
            "✓ src/auth.test.ts        (14)",
            "✓ src/router.test.ts      (9)",
            "✓ src/cache.test.ts       (11)",
            "",
            "Test Files  3 passed (3)",
            "     Tests  34 passed (34)",
            "  Duration  3.06s"
          ],
          "style": "ok"
        },
        {
          "cmd": "git commit -am \"feat: edge cache + auth guard\""
        },
        {
          "out": [
            "[main 9f3c2a1] feat: edge cache + auth guard",
            " 6 files changed, 218 insertions(+), 41 deletions(-)"
          ],
          "style": "dim"
        },
        {
          "out": "● working tree clean → ready to push",
          "style": "accent",
          "stream": 1.4
        }
      ]
    }
  },
  {
    "id": "iterm2-p10k",
    "name": "iTerm2 · Powerlevel10k",
    "blurb": "powerline segments · two-line git prompt",
    "sw": "#00d7af",
    "scene": {
      "meta": {
        "aspect": "wide",
        "theme": {
          "preset": "iterm2"
        },
        "window": {
          "chrome": "mac",
          "title": "iTerm2"
        },
        "prompt": "❯",
        "fontSize": 24
      },
      "steps": [
        {
          "cmd": "git status",
          "prompt": " ~/projects/brand-engine   main ✔   node v20 "
        },
        {
          "out": [
            "On branch main",
            "Your branch is up to date with 'origin/main'.",
            "",
            "nothing to commit, working tree clean"
          ],
          "style": "dim"
        },
        {
          "cmd": "git checkout -b feat/streaming-tokens",
          "prompt": " ~/projects/brand-engine   main ✔   node v20 "
        },
        {
          "out": "Switched to a new branch 'feat/streaming-tokens'"
        },
        {
          "cmd": "nvim src/pipeline/stream.ts",
          "prompt": " ~/projects/brand-engine   feat/streaming-tokens ✔   node v20 "
        },
        {
          "cmd": "git status -s",
          "prompt": " ~/projects/brand-engine   feat/streaming-tokens ✚1   node v20 "
        },
        {
          "out": " M src/pipeline/stream.ts",
          "style": "warn"
        },
        {
          "cmd": "git commit -am 'feat: stream Opus tokens via SSE'",
          "prompt": " ~/projects/brand-engine   feat/streaming-tokens ✚1   node v20 "
        },
        {
          "out": [
            "[feat/streaming-tokens 9c1af7e] feat: stream Opus tokens via SSE",
            " 1 file changed, 34 insertions(+), 6 deletions(-)"
          ],
          "style": "ok"
        },
        {
          "cmd": "git push -u origin feat/streaming-tokens",
          "prompt": " ~/projects/brand-engine   feat/streaming-tokens ✔   node v20 "
        },
        {
          "progress": "Writing objects to origin",
          "duration": 1.6
        },
        {
          "out": [
            "remote: ",
            "remote: Create a pull request for 'feat/streaming-tokens' on GitHub by visiting:",
            "remote:   https://github.com/santos/brand-engine/pull/new/feat/streaming-tokens",
            "To github.com:santos/brand-engine.git",
            " * [new branch]      feat/streaming-tokens -> feat/streaming-tokens",
            "branch 'feat/streaming-tokens' set up to track 'origin/feat/streaming-tokens'."
          ],
          "style": "dim"
        },
        {
          "cmd": "gh pr create --fill --web",
          "prompt": " ~/projects/brand-engine   feat/streaming-tokens ✔   node v20 "
        },
        {
          "out": "Opening github.com/santos/brand-engine/pull/247 in your browser  ✓",
          "style": "accent",
          "stream": 1.4
        }
      ]
    }
  },
  {
    "id": "macos-zsh",
    "name": "macOS Terminal",
    "blurb": "white bg · black SF Mono · the everyman shell",
    "sw": "#cfcfcf",
    "scene": {
      "meta": {
        "aspect": "wide",
        "theme": {
          "preset": "macos"
        },
        "window": {
          "chrome": "mac",
          "title": "zsh — 80×24"
        },
        "prompt": "dev@mac ~ %",
        "fontSize": 24
      },
      "steps": [
        {
          "cmd": "brew update"
        },
        {
          "out": [
            "==> Updating Homebrew...",
            "Already up-to-date."
          ],
          "style": "dim"
        },
        {
          "cmd": "brew install jq"
        },
        {
          "out": [
            "==> Fetching jq",
            "==> Downloading https://ghcr.io/v2/homebrew/core/jq/manifests/1.7.1"
          ],
          "style": "dim"
        },
        {
          "progress": "==> Downloading jq--1.7.1.arm64_sequoia.bottle.tar.gz",
          "duration": 2.4
        },
        {
          "out": [
            "==> Pouring jq--1.7.1.arm64_sequoia.bottle.tar.gz",
            "==> Summary",
            "  /opt/homebrew/Cellar/jq/1.7.1: 31 files, 1.2MB"
          ],
          "style": "dim"
        },
        {
          "div": true
        },
        {
          "cmd": "curl -s https://api.github.com/repos/jqlang/jq | jq .stargazers_count"
        },
        {
          "out": "31487"
        },
        {
          "cmd": "git -C ~/projects/dotfiles status -sb"
        },
        {
          "out": [
            "## main...origin/main",
            " M zsh/.zshrc",
            "?? brew/Brewfile.lock.json"
          ]
        },
        {
          "cmd": "echo \"$(jq --version) ready\""
        },
        {
          "out": "jq-1.7.1 ready",
          "style": "ok",
          "stream": 1.2
        }
      ]
    }
  },
  {
    "id": "ubuntu-bash",
    "name": "Ubuntu Terminal",
    "blurb": "aubergine #300a24 · green user@host · peak Linux",
    "sw": "#8ae234",
    "scene": {
      "meta": {
        "aspect": "wide",
        "theme": {
          "preset": "ubuntu"
        },
        "window": {
          "chrome": "plain",
          "title": "dev@ubuntu: ~"
        },
        "prompt": "dev@ubuntu:~$",
        "fontSize": 24
      },
      "steps": [
        {
          "cmd": "sudo apt update"
        },
        {
          "out": [
            "Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease",
            "Hit:2 http://security.ubuntu.com/ubuntu noble-security InRelease",
            "Get:3 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]",
            "Fetched 126 kB in 1s (171 kB/s)",
            "Reading package lists... Done",
            "Building dependency tree... Done",
            "Checking package upgradability... Done"
          ],
          "style": "dim"
        },
        {
          "out": "18 packages can be upgraded. Run 'apt list --upgradable' to see them.",
          "style": "warn"
        },
        {
          "cmd": "sudo apt upgrade -y"
        },
        {
          "progress": "Unpacking and configuring 18 packages",
          "duration": 3.5
        },
        {
          "out": [
            "Setting up linux-image-6.11.0-29-generic (6.11.0-29.29) ...",
            "Processing triggers for man-db (2.12.0-4) ...",
            "Processing triggers for initramfs-tools (0.142ubuntu25.5) ..."
          ],
          "style": "dim"
        },
        {
          "div": true
        },
        {
          "cmd": "sudo systemctl restart nginx && systemctl status nginx --no-pager"
        },
        {
          "out": [
            "● nginx.service - A high performance web server and a reverse proxy server",
            "     Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; preset: enabled)",
            "     Active: active (running) since Fri 2026-06-12 09:14:02 UTC; 11ms ago",
            "   Main PID: 4471 (nginx)",
            "      Tasks: 5 (limit: 9489)",
            "     Memory: 5.2M (peak: 6.1M)"
          ],
          "style": "ok"
        },
        {
          "cmd": "df -h /"
        },
        {
          "out": [
            "Filesystem      Size  Used Avail Use% Mounted on",
            "/dev/nvme0n1p2   78G   31G   43G  42% /"
          ]
        },
        {
          "out": "all systems nominal -- kernel staged, reboot at next maintenance window.",
          "style": "ok",
          "stream": 1.5
        }
      ]
    }
  },
  {
    "id": "starship",
    "name": "Starship",
    "blurb": "segmented prompt · morphs per language/repo",
    "sw": "#88c0d0",
    "scene": {
      "meta": {
        "aspect": "wide",
        "theme": {
          "preset": "starship"
        },
        "window": {
          "chrome": "mac",
          "title": "starship"
        },
        "prompt": "❯",
        "fontSize": 24
      },
      "steps": [
        {
          "cmd": "cargo build --release",
          "prompt": " ~/rust-svc   main  rust v1.84 "
        },
        {
          "out": [
            "   Compiling rust-svc v0.4.1 (/home/dev/rust-svc)",
            "    Finished `release` profile [optimized] in 8.31s"
          ],
          "style": "dim"
        },
        {
          "cmd": "cd ../node-api",
          "prompt": " ~/rust-svc   main  rust v1.84 "
        },
        {
          "cmd": "pnpm test",
          "prompt": " ~/node-api   main  ⬢ node v22.14 "
        },
        {
          "out": [
            " ✓ src/routes.test.ts (14)",
            "   Test Files  1 passed (1)",
            "        Tests  14 passed (14)",
            "     Duration  612ms"
          ],
          "style": "ok"
        },
        {
          "cmd": "cd ../py-worker && git status -sb",
          "prompt": " ~/node-api   main  ⬢ node v22.14 "
        },
        {
          "out": [
            "## main...origin/main",
            " M tasks/ingest.py"
          ],
          "style": "warn"
        },
        {
          "cmd": "uv run ruff check .",
          "prompt": " ~/py-worker   main !1  py v3.13 "
        },
        {
          "out": "All checks passed!",
          "style": "ok"
        },
        {
          "cmd": "git commit -am \"fix: stream ingest in chunks\"",
          "prompt": " ~/py-worker   main !1  py v3.13   42s "
        },
        {
          "out": [
            "[main 9f2c1ab] fix: stream ingest in chunks",
            " 1 file changed, 7 insertions(+), 3 deletions(-)"
          ],
          "style": "accent",
          "stream": 1.4
        }
      ]
    }
  }
]

export interface JobTemplate {
  id: string
  name: string
  tagline: string
  /** where's this going? — drives aspect + recommended export format */
  destination: string
  sw: string
  scene: Scene
}

// JOB-FIRST templates — the primary on-ramp shown on first load.
export const JOB_TEMPLATES: JobTemplate[] = [
  {
    "id": "agent-demo",
    "name": "Agent demo",
    "tagline": "An AI coding agent finishes a real task",
    "destination": "readme",
    "sw": "#d97757",
    "scene": {
      "meta": {
        "aspect": "square",
        "theme": {
          "preset": "claude"
        },
        "window": {
          "chrome": "mac",
          "title": "claude code"
        },
        "align": "top",
        "prompt": "❯",
        "fontSize": 24,
        "loopOffset": "80%"
      },
      "steps": [
        {
          "cmd": "fix the failing test in the orders module",
          "typeSpeed": 46
        },
        {
          "wait": 0.3
        },
        {
          "out": "✻ Thinking… the partial-refund test is red — let me find where the amount is computed.",
          "style": "dim",
          "stream": 1.2
        },
        {
          "out": [
            "● Grep(\"partial_refund\", src/orders/)  3 matches",
            "● Read(src/orders/refund.py:40-60)",
            "● Edit(src/orders/refund.py +2 -1)"
          ],
          "style": "accent"
        },
        {
          "out": "● Bash(pytest tests/test_orders.py -q)",
          "style": "accent"
        },
        {
          "progress": "running 48 tests",
          "duration": 1.8,
          "style": "accent"
        },
        {
          "out": "✓ 48 passed in 0.9s",
          "style": "ok"
        },
        {
          "div": true
        },
        {
          "out": [
            "● Fixed. The fee was subtracted after rounding, double-counting it;",
            "  rounding now happens last. All 48 tests green."
          ],
          "style": "ok",
          "stream": 1.6
        }
      ]
    }
  },
  {
    "id": "product-demo",
    "name": "Product demo",
    "tagline": "Show your AI product doing its job perfectly",
    "destination": "social",
    "sw": "#58a6ff",
    "scene": {
      "meta": {
        "aspect": "square",
        "theme": {
          "preset": "midnight",
          "accent": "#34d399",
          "ok": "#34d399"
        },
        "window": {
          "chrome": "mac",
          "title": "atlas — support agent"
        },
        "align": "top",
        "prompt": "❯",
        "fontSize": 24,
        "typeSpeed": 46
      },
      "steps": [
        {
          "cmd": "atlas \"refund order 80421 and tell the customer why it was late\""
        },
        {
          "wait": 0.3
        },
        {
          "out": "✦ Pulling the order, the shipment trace, and the refund policy.",
          "style": "dim",
          "stream": 1.4
        },
        {
          "out": [
            "┌─ check ──────────────┬─ result ───────────────────────────",
            "● order   80421        │  $74.00 · 2 items",
            "● trace   shipment     │  stuck 3d at MEM hub",
            "● policy  late_delivery│  eligible · full refund",
            "└──────────────────────┴────────────────────────────────────"
          ],
          "style": "accent",
          "lineDelay": 0.18
        },
        {
          "wait": 0.4
        },
        {
          "out": [
            "Carrier held it at the Memphis hub for 3 days — that's on us, so a full",
            "refund qualifies. Issuing it and drafting the apology now."
          ],
          "stream": 2
        },
        {
          "out": [
            "● refund(order 80421)   $74.00 → card ···4417   ✓",
            "● email(customer)       sent · \"sorry it ran late\""
          ],
          "style": "accent",
          "lineDelay": 0.18
        },
        {
          "div": true
        },
        {
          "out": "✦ Done. Refunded $74.00 and emailed the customer the reason. Avg handle time: 9s.",
          "style": "ok",
          "stream": 1.6
        }
      ]
    }
  },
  {
    "id": "launch-clip",
    "name": "Launch clip",
    "tagline": "A scroll-stopping deploy → live URL, vertical",
    "destination": "story",
    "sw": "#58a6ff",
    "scene": {
      "meta": {
        "aspect": "square",
        "theme": {
          "preset": "midnight",
          "accent": "#7c5cff"
        },
        "window": {
          "chrome": "mac",
          "title": "shipd"
        },
        "align": "center",
        "fontSize": 24,
        "typeSpeed": 40
      },
      "steps": [
        {
          "cmd": "shipd deploy",
          "holdBeforeEnter": 0.15
        },
        {
          "out": "◇ detecting framework... Next.js",
          "style": "dim"
        },
        {
          "progress": "building",
          "duration": 1.3,
          "style": "accent"
        },
        {
          "progress": "uploading",
          "duration": 1.1,
          "style": "accent"
        },
        {
          "out": [
            "✓ 0 cold starts",
            "✓ edge in 38 regions"
          ],
          "style": "ok"
        },
        {
          "div": true
        },
        {
          "out": "● live → acme.shipd.app",
          "style": "accent",
          "stream": 0.9
        },
        {
          "out": "  shipped in 6s.",
          "style": "accent",
          "stream": 0.8
        },
        {
          "wait": 1.4
        }
      ]
    }
  },
  {
    "id": "bug-repro",
    "name": "Bug repro",
    "tagline": "Paste a failing command + error onto an issue",
    "destination": "readme",
    "sw": "#58a6ff",
    "scene": {
      "meta": {
        "aspect": "square",
        "theme": {
          "preset": "midnight"
        },
        "window": {
          "chrome": "plain",
          "title": "bash — repro"
        },
        "align": "top",
        "fontSize": 24,
        "prompt": "$"
      },
      "steps": [
        {
          "cmd": "pytest tests/test_orders.py::test_partial_refund -q"
        },
        {
          "out": "collected 1 item",
          "style": "dim"
        },
        {
          "out": [
            "tests/test_orders.py:48: in test_partial_refund",
            ">       assert refund.amount == Decimal(\"4.50\")"
          ],
          "style": "dim"
        },
        {
          "out": "E       assert Decimal('4.99') == Decimal('4.50')",
          "style": "err"
        },
        {
          "out": [
            "E        +  where Decimal('4.99') = Refund(line_total=4.99, fee=0.49).amount"
          ],
          "style": "err"
        },
        {
          "div": true
        },
        {
          "out": "1 failed in 0.21s",
          "style": "err"
        },
        {
          "out": "# rounding the fee before the subtraction double-counts it",
          "style": "warn",
          "stream": 0.8
        }
      ]
    }
  },
  {
    "id": "lesson",
    "name": "Teach a command",
    "tagline": "A clean before/after for a deck or course",
    "destination": "deck",
    "sw": "#a8442a",
    "scene": {
      "meta": {
        "aspect": "square",
        "theme": {
          "preset": "paper"
        },
        "window": {
          "chrome": "mac",
          "title": "lesson — git rebase"
        },
        "align": "center",
        "fontSize": 24,
        "typeSpeed": 16,
        "marginPad": 56,
        "marginFill": "#e7e2d6"
      },
      "steps": [
        {
          "out": "# replay your commits on top of main — no merge bubble",
          "style": "dim"
        },
        {
          "wait": 0.5
        },
        {
          "cmd": "git rebase main",
          "holdBeforeEnter": 0.5
        },
        {
          "out": [
            "Successfully rebased and updated refs/heads/feature.",
            ""
          ],
          "style": "ok"
        },
        {
          "div": true
        },
        {
          "out": "# now the history is a straight line:",
          "style": "dim"
        },
        {
          "cmd": "git log --oneline --graph -4",
          "holdBeforeEnter": 0.5
        },
        {
          "out": [
            "* 4a1c9f2  feat: add export button",
            "* 9c3b1a7  feat: csv writer",
            "* e7d22f0  chore: deps",
            "* 1b9f034  (main) docs: readme"
          ],
          "style": "accent"
        },
        {
          "wait": 1.2
        }
      ]
    }
  }
]

// accent color per theme preset — for swatch chips in the structured controls.
export const THEME_ACCENT: Record<string, string> = {
  "claude": "#d97757",
  "gemini": "#a78bfa",
  "codex": "#10a37f",
  "warp": "#4c8dff",
  "iterm2": "#00d7af",
  "macos": "#cfcfcf",
  "ubuntu": "#8ae234",
  "starship": "#88c0d0",
  "midnight": "#58a6ff",
  "matrix": "#37d837",
  "paper": "#a8442a",
  "kiro": "#9046ff"
}
